#!/bin/bash
#SBATCH --job-name=L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0          # Name of the job
#SBATCH --time=7-00:00:00               # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=1               # Number of nodes
#SBATCH --ntasks=32
#SBATCH --output=/home/x_ilama/3Component_LondonModel/Output_3C/e_0.5/nu_0.2/h_1/L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0/logs/log_L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0.o
#SBATCH --error=/home/x_ilama/3Component_LondonModel/Output_3C/e_0.5/nu_0.2/h_1/L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0/logs/log_L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0.e

srun ../build/Release/LondonModel_3component 12 /home/x_ilama/3Component_LondonModel/Output_3C/e_0.5/nu_0.2/h_1/L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0 /home/x_ilama/3Component_LondonModel/Output_3C/e_0.5/nu_0.2/h_1/L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0 0 &> /home/x_ilama/3Component_LondonModel/Output_3C/e_0.5/nu_0.2/h_1/L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0/logs/log_L12_rho1_eta1_e0.5_h1_nu0.2_bmin0.5_bmax5.0.o


