#!/bin/bash
#SBATCH --job-name=L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5          # Name of the job
#SBATCH --time=7-00:00:00               # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=1               # Number of nodes
#SBATCH --ntasks=32
#SBATCH --output=/home/cluster_users/x_ilaria/3Component_LondonModel/Output_3C/e_0/nu_0.5/h_1/L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5/logs/log_L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5.o
#SBATCH --error=/home/cluster_users/x_ilaria/3Component_LondonModel/Output_3C/e_0/nu_0.5/h_1/L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5/logs/log_L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5.e
#SBATCH --qos=urgent

srun ../build/Release/LondonModel_3component 12 /home/cluster_users/x_ilaria/3Component_LondonModel/Output_3C/e_0/nu_0.5/h_1/L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5 /home/cluster_users/x_ilaria/3Component_LondonModel/Output_3C/e_0/nu_0.5/h_1/L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5 0 &> /home/cluster_users/x_ilaria/3Component_LondonModel/Output_3C/e_0/nu_0.5/h_1/L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5/logs/log_L12_rho1_eta1_e0_h1_nu0.5_bmin0.25_bmax0.5.o


